# Introduction

Here I will list all the markdown formatting that I may use in the notebook

<br>


## Subheaders
### Subsubheader
#### I don't even know whether I'll used this header

<br><br>A lot of breaks with `<br>`
<br> 

*Italic* keywords
> Highlights or key ideas with a nice little indent over here

Some Hyperlinks, like this one: [00 Introduction](http://localhost:8889/notebooks/Documents/GitHub/PartIA-Computing-Michaelmas/01%20Variables%2C%20assignment%20and%20operator%20precedence.ipynb)
 <br><br>

- Bullet points


1. Lists, and its interesting how you only need to type 1. for all of them
1. and also separate 2 normal lines between bullet points and enumerated lists

<br>


`Some code` within sentences, or

```python
print("Some Python Code (that is just for show)")
```

<br>


Some $\LaTeX equations \; or \; variables$ within text, or
$$
\int \; \LaTeX \; \textit{Equation}x \; dx
$$





# Course Content


0. [Structure](00%20Part%20IA%20Michaelmas%20Term%20computing.ipynb)
1. [Variables, assignment and operator precedence](01%20Variables,%20assignment%20and%20operator%20precedence.ipynb)
1. [Control statements](02%20Control%20statements.ipynb)
1. [Types, type conversions and floating point arithmetic](03%20Types,%20type%20conversions%20and%20floating%20point%20arithmetic.ipynb)
1. [Functions](04%20Functions.ipynb)
1. [Library functions](05%20Library%20functions.ipynb)
1. [Data structures](06%20Data%20structures.ipynb)
1. [Numerical computation](07%20Numerical%20computation.ipynb)
1. [Plotting](08%20Plotting.ipynb)
1. [Error handling and testing](09%20Error%20handling%20and%20testing.ipynb)
1. [Algorithms](10%20Algorithms.ipynb)
1. [Complexity](11%20Complexity.ipynb)
1. [Object-oriented design](12%20Object-oriented%20design.ipynb)

# 01 Variables, assignment and operator precedence

### Operations

In [40]:
print(2 ** 8)
print(11 % 3)
print(11 // 3)

256
2
3


### Shortcuts

In [41]:
a = 12
a *= 4
print(a)

48


### $\LaTeX$ Symbols
LaTeX Commands within code: <br>
Type `'\theta'` followed by `tab` key

In [42]:
α = 10
β = 20
γ = α + β
print(γ)

30


# 02 Control statements

### Boolean Operators

In [43]:
print(10 < 9 or not 15 < 20 or 10 != 10)

False


### `if`

In [44]:
x = -10.0

if x > 0.0:  
    print('Initial x is greater than zero')
elif x < 0.0:  
    print('Initial x is less than zero')
else: 
    print('Initial x is not less than zero and not greater than zero, therefore it must be zero')

Initial x is less than zero


### `for`

In [45]:
for n in range(4):
    print(n, n**2)
print("----")
for n in range(0, 10, 3):
    print(n)

0 0
1 1
2 4
3 9
----
0
3
6
9


### `while`

In [46]:
x = -2
while x < 5:
    print(x)
    x += 1  # Increment x

-2
-1
0
1
2
3
4


### `break`

In [47]:
for x in range(10):
    print(x)
    if x == 5:
        print("Time to break out")
        break

0
1
2
3
4
5
Time to break out


### `continue`

In [48]:
for j in range(20):
    if j % 4 != 0:  # Check remained of j/4
        continue  # jump to next iteration over j
    print("Number is divisible by 4:", j)

Number is divisible by 4: 0
Number is divisible by 4: 4
Number is divisible by 4: 8
Number is divisible by 4: 12
Number is divisible by 4: 16


### `pass`

In [49]:
for x in range(10):
    if x < 5:
        # TODO: implement handling of x < 5 when other cases finished (fake TODO btw)
        pass
    elif x < 9:
        print(x*x)
    else:
        print(x)

25
36
49
64
9


# 03 Types, type conversions and floating point arithmetic

### Types

In [50]:
print(type(True))
print(type(0.50 + 2j))
print(type("This is a string"))

<class 'bool'>
<class 'complex'>
<class 'str'>


In [51]:
b = 4-3J
print(b.imag, b.real, b.conjugate(), abs(b))

-3.0 4.0 (4+3j) 5.0


### Integer Overflow
Gangnam style: $2^{31}$ views, YouTube switched from 32-bit to 64-bit integers to count views.<br>
Boeing 787 Dreamliner: electricity shuts down if plane powered 248 days continuously ($2^{31} \times 0.01$ seconds)

In [52]:
a = 8
print(a.bit_length())
b = a**12
print(b.bit_length()) #This would exceed 32 bits

4
37


### Floating point storage
$$
10.45 = \underbrace{+}_{\text{sign}} \underbrace{1045}_{\text{significand}} \times \underbrace{10^{-2}}_{\text{exponent} = -2}
$$

In [53]:
x = 0.1
print('x in 30 characters: ')
print('{0:.30f}'.format(x))
for i in range(20):
    x = x*11 - 1
    print(x)
# This is caused by the fact that 0.1 here is represented by a 64 bit binary approximation.
# By default, Python uses 64 bits to store a float, but we can use numpy to create 32 bit floats and more.

x in 30 characters: 
0.100000000000000005551115123126
0.10000000000000009
0.10000000000000098
0.10000000000001075
0.10000000000011822
0.10000000000130038
0.1000000000143042
0.10000000015734622
0.10000000173080847
0.10000001903889322
0.10000020942782539
0.10000230370607932
0.10002534076687253
0.10027874843559781
0.1030662327915759
0.13372856070733485
0.4710141677806834
4.181155845587517
44.992714301462684
493.9198573160895
5432.118430476985


Patriot Missle Failure: missle software multiplied counter by float representation of $0.1$ in 24 bits, and it lead to an error of $0.32\,$s  after 100 hours of operation, and due to the high velocity of the missile it failed to intercept the incoming Scud.

In [54]:
import numpy as np
# Compute internal system counter after 100 hours (counter increments every 1/10 s)
num_hours = 100
num_seconds = num_hours*60*60
system_counter = num_seconds*10  # system clock counter

# Test with 16 bit float
dt = np.float16(0.1)
time = dt*system_counter
print("Time error after 100 hours using 16 bit float (s):", abs(time - num_seconds))

# Test with 32 bit float
dt = np.float32(0.1)
time = dt*system_counter
print("Time error after 100 hours using 32 bit float (s):", abs(time - num_seconds))

# Test with 64 bit float
dt = np.float64(0.1)
time = dt*system_counter
print("Time error after 100 hours using 64 bit float (s):", abs(time - num_seconds))

Time error after 100 hours using 16 bit float (s): 87.890625
Time error after 100 hours using 32 bit float (s): 0.005364418029785156
Time error after 100 hours using 64 bit float (s): 0.0


# 04 Functions

### Named arguments

In [55]:
def subtract_and_increment(a, b):
    "Return a minus b, plus 1"
    return a - b + 1
alpha, beta = 3, 5
print(subtract_and_increment(a=alpha, b=beta))  # Expect -1
print(subtract_and_increment(b=beta, a=alpha))  # Expect -1

-1
-1


### Passing a function as a function argument

In [56]:
def f_minus_10(x):
    return x-10
def is_positive(f, x):
    "Check if the function value f(x) is positive"
    # Evaluate the function passed into the function for the value of x 
    # passed into the function
    if f(x) > 0:
        return True, f(x)
    else:
        return False, f(x)
print(is_positive(f_minus_10, 8))

(False, -2)


### Recursive Functions

In [57]:
def f(n): 
    "Compute the nth Fibonacci number using recursion"
    if n == 0:
        return 0  # This doesn't call f, so it breaks out of the recursion loop
    elif n == 1:
        return 1  # This doesn't call f, so it breaks out of the recursion loop
    else:
        return f(n - 1) + f(n - 2)  # This calls f for n-1 and n-2 (recursion), and returns the sum 

print(f(10))

55


In [58]:
"My recursive function to compute a root"

def testf(x): # Test function with obvious roots 4 and -4
    return x**2 - 16
def my_f(x): # Function to be used
    "Evaluate polynomial function"
    return x**3 - 6*x**2 + 4*x + 12

def compute_root(f, x0, x1, tol, max_it, it_count=0): # it_count initialized in the argument part of the def
    "Compute roots of a function using bisection, recusive function"
    # increment it_count
    it_count += 1
    
    # bisection and reassigning boundary values
    x_mid = (x0 + x1)/2
    if f(x_mid)*f(x0) < 0:
        x1 = x_mid
    else:
        x0 = x_mid
    
    # Break if error is under tolerance
    error = abs(f(x_mid))
    if error < tol:
        return x_mid, f(x_mid), it_count
    
    # Break 
    if it_count >= max_it:
        print("Maximum Iterations Reached - will show results with ", it_count, " iterations.")
        return x_mid, f(x_mid), it_count
    
    # Call compute_root recursively
    return compute_root(f, x0, x1, tol, max_it, it_count)

# Testing my code with the testf (root is 4 and -4) and my_f
x, f, num_it = compute_root(testf, x0=3, x1=6, tol=1.0e-6, max_it=1000)
print(x, f, num_it)
x, f, num_it = compute_root(my_f, x0=3, x1=6, tol=1.0e-6, max_it=1000)
print(x, f, num_it)
print( round(x - 4.534070134162903, 10) == 0.0)

4.0000001192092896 9.536743306171047e-07 23
4.534070134162903 -7.047073751209609e-07 23
True


# Library functions

In [59]:
import math

x = 2.0
x = math.sqrt(x)
print(x)

1.4142135623730951


In [60]:
from math import sqrt as square_root

x = 2.0
x = square_root(x)
print(x)

1.4142135623730951


### String Formatting

In [61]:
import math
print("{}".format(math.pi))
print("{:.8}".format(math.pi))
print("{:.20e}".format(math.pi))

3.141592653589793
3.1415927
3.14159265358979311600e+00


A very nice compression exercise: [05 Exercises](http://localhost:8888/notebooks/Documents/GitHub/PartIA-Computing-Michaelmas/Exercises/05%20Exercises.ipynb)

Failed - [Sorting Example]("05%20Library%20functions.ipynb")

# 06 Data structures

In [62]:
lab_group0 = ["Sarah", "John", "Joe", "Emily"]
lab_group1 = ["Roger", "Rachel", "Amer", "Caroline", "Colin"]
print([lab_group0, lab_group1])
print(lab_group0 + lab_group1)

[['Sarah', 'John', 'Joe', 'Emily'], ['Roger', 'Rachel', 'Amer', 'Caroline', 'Colin']]
['Sarah', 'John', 'Joe', 'Emily', 'Roger', 'Rachel', 'Amer', 'Caroline', 'Colin']


In [63]:
lab_group0 = ["Sarah", "John", "Joe", "Emily"]
for member in lab_group0:
    print(member)
print("----")
for n, member in enumerate(lab_group0):
    print(n, member)

Sarah
John
Joe
Emily
----
0 Sarah
1 John
2 Joe
3 Emily


In [64]:
lab_group0 = ["Sarah", "John", "Joe", "Emily"]

# Remove the second student (indexing starts from 0, so 1 is the second element)
lab_group0.pop(1)
print(lab_group0)

# Add new student "Josephine" at the end of the list
lab_group0.append("Josephine")
print(lab_group0)

['Sarah', 'Joe', 'Emily']
['Sarah', 'Joe', 'Emily', 'Josephine']


In [65]:
lab_group0 = ["Sarah", "John", "Joe", "Emily"]
for i in range(len(lab_group0)):
    print(lab_group0[i])

Sarah
John
Joe
Emily


In [66]:
lab_group0 = ["Sarah", "John", "Joe", "Emily"]
lab_group0.sort()
print(lab_group0)

print("----")

lab_group0 = ["Sarah", "John", "Joe", "Emily"]
sorted_lab_group0 = sorted(lab_group0)
print(lab_group0)
print(sorted_lab_group0)

['Emily', 'Joe', 'John', 'Sarah']
----
['Sarah', 'John', 'Joe', 'Emily']
['Emily', 'Joe', 'John', 'Sarah']


### List Comprehension
(Basically shortcut)

In [67]:
lab_group1 = ["Roger", "Rachel", "Amer", "Caroline", "Colin"]
group = [name + "." for name in lab_group1 if len(name) > 5]
print(group)

['Rachel.', 'Caroline.']


In [68]:
"Finding the sum vector of a and b"
a = [0, 4.3, -5, 7]
b = [-2, 7, -15, 1]
print( [a[i] + b[i] for i in range(len(a))] ) # the first method that came to my mind
# OR
print(list(zip(a,b))) # To show what list(zip(a,b)) really is
print( [x+y for x,y in list(zip(a,b))] )

[-2, 11.3, -20, 8]
[(0, -2), (4.3, 7), (-5, -15), (7, 1)]
[-2, 11.3, -20, 8]


### Dictionaries and operations

In [69]:
names_to_abbrev = {'St Catharine\'s': 'CTH',
                   'Christ\'s': 'CHR', 
                   'Churchill': 'CHU', 
                   'Clare':'CL', 
                   'Clare Hall':'CLH', 
                   'Corpus Christi': 'CC'}
print(names_to_abbrev, '\n') # Testing this list

"Inversing the list"
abbrev_to_names = {}
for name, abbrev in names_to_abbrev.items(): # .items() gets both key and value
    abbrev_to_names[abbrev] = name
print('Dictionary from college abbrev to name:\n', abbrev_to_names)
    
"Sorting the abbreviation list"
abbrev_list = [abbrev for abbrev in abbrev_to_names] # List comprehension
abbrev_list.sort()
print('\nSorted abbreviation list:\n', abbrev_list)

{"St Catharine's": 'CTH', "Christ's": 'CHR', 'Churchill': 'CHU', 'Clare': 'CL', 'Clare Hall': 'CLH', 'Corpus Christi': 'CC'} 

Dictionary from college abbrev to name:
 {'CTH': "St Catharine's", 'CHR': "Christ's", 'CHU': 'Churchill', 'CL': 'Clare', 'CLH': 'Clare Hall', 'CC': 'Corpus Christi'}

Sorted abbreviation list:
 ['CC', 'CHR', 'CHU', 'CL', 'CLH', 'CTH']


In [70]:
# One key can have more than 1 value using a list or tuple:
cambridge_colleges = {'St Catharine\'s': ('CTH', 1473, 768),
                   'Christ\'s': ('CHR', 1505, 689), 
                   'Churchill': ('CHU', 1960, 845), 
                   'Clare': ('CL', 1326, 808), 
                   'Clare Hall': ('CLH', 1966, 249), 
                   'Corpus Christi': ('CL', 1352, 553)}

In [71]:
# This is method two found online: dictionary within dictionary
my_dict = {
	"my_key": {
		"key_1": 'value_1', 
		"key_2": 'value_2'
	}
}
print (my_dict["my_key"]["key_1"])  # This will print value_1
print (my_dict["my_key"]["key_2"])  # This will print value_2

value_1
value_2


# 07 Numerical computation

### NumPy 1D Arrays

In [29]:
import numpy as np

print(np.zeros(6))
print(np.ones(10))
print(np.random.rand(3))

print(np.arange(2,10))       # It is Array RANGE hence arange
print(np.array(range(2,10))) # Same thing as above


print(np.linspace(0,100,6))  # Used extensively for plotting

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.84314081 0.0397491  0.61188414]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[  0.  20.  40.  60.  80. 100.]


In [30]:
x = np.zeros(6)

print(x)
print(type(x))
print(len(x))
print(x.dtype) # Dimensional Type (of the values)
print(x.shape) # Shape - axbxc matrice gives (a,b,c)

[0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
6
float64
(6,)


In [31]:
"Indexing - same as python lists"
x[0] = 10
x[5] = 5
print(x)

[10.  0.  0.  0.  0.  5.]


In [32]:
"NumPy array from python list"
x = [4.0, 8.0, 9.0, 11.0, -2.0]
y = np.array(x)
print(y)

[ 4.  8.  9. 11. -2.]


### Arithmetic

In [47]:
x = np.array([1, 2, 4])
y = np.array([0, np.pi/2, np.pi])
print(x)
print(y, "\n")

print(x + y)
print(x * y)
print(x * 2)
print(x ** 2, "\n")

print(np.sin(y)) # Not math.sin though

[1 2 4]
[0.         1.57079633 3.14159265] 

[1.         3.57079633 7.14159265]
[ 0.          3.14159265 12.56637061]
[2 4 8]
[ 1  4 16] 

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
