Make NumPy available:

In [59]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [60]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [83]:
"Create 2 very long arrays"
length = 10000000
x = np.random.rand(length)
y = np.random.rand(length)

#### (1) Add two vectors using built-in addition operator:

In [84]:
# YOUR CODE HERE
def built_in_addition(a,b):
    return a + b
%time answer = built_in_addition(x,y)

Wall time: 36.9 ms


#### (2) Add two vectors using own implementation:

In [85]:
# YOUR CODE HERE
def own_implementation(a,b):
    c = np.zeros(len(a))
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

%time answer = own_implementation(x,y)
        

Wall time: 3.58 s


### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [86]:
!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

Wall time: 2.82 s
Wall time: 49.9 ms


**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

In [88]:
import numba

@numba.jit
def own_implementation_jit(a,b):
    c = np.zeros(len(a))
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

%time answer = own_implementation_jit(x,y)

#it is much faster wow

Wall time: 139 ms


## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [112]:
def to_percentage_and_sort(scores):
    # YOUR CODE HERE
    scores  = scores * 100 / 60
    scores.sort()
    return scores

def statistics(scores, exclude=False):
    # YOUR CODE HERE
    if exclude == True:
        scores.sort()
        scores = scores[1:-1]
    print(scores)
    dictionary = {"min": scores.min(), "max": scores.max(), "mean": scores.mean()}
    return dictionary

scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
print(to_percentage_and_sort(scores))
print(statistics(scores))

[13.         40.         58.33333333 70.         96.66666667]
[58.  35.  24.  42.   7.8]
{'min': 7.8, 'max': 58.0, 'mean': 33.36}


In [113]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

[58.  35.  24.  42.   7.8]
[24. 35. 42.]


## Exercise 07.3 (slicing)

For the two-dimensional array

In [115]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [116]:
# YOUR CODE HERE
print(A[:, 2])

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [122]:
# YOUR CODE HERE
print(A[:2, :])

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [123]:
# YOUR CODE HERE
print(A[-2:, -2:])

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [129]:
# YOUR CODE HERE
last_column = A[:, 3]
print(last_column)
print(last_column[1])

summ = 0
for n in last_column:
    summ += n
print(summ)

[ 67.1   -3.33   4.11 323.22]
-3.33
391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [131]:
# YOUR CODE HERE
print(A.transpose())

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [170]:
"FAILFAILFAIL NEED REVIEW"

from scipy import optimize

# YOUR CODE HERE

def my_f(x):
    "Evaluate polynomial function"
    return x**3 - 6*x**2 + 4*x + 12
def testf(x):
    return x**2 - 16

def compute_root(f, x0, x1, tol, max_it):
    "Compute roots of a function using bisection"
    
    error = tol + 1
    it = 0
    
    while error > tol:
        x_mid = (x0 + x1)/2

        if f(x_mid)*f(x0) < 0:
            x1 = x_mid
        else:
            x0 = x_mid
            
        error = abs(f(x_mid))
        
        # Guard against infinite loop
        it += 1
        if it >= max_it:
            print("Error - iteration count exceeded maximum of ", max_it)
            # print("Breaking out of while loop") # Debug message
            break

    # Return the approximate root, value of f(x) and the number of iterations 
    return x_mid, f(x_mid), it

%time x, f, num_it = compute_root(testf, x0=3, x1=6, tol=1.0e-15, max_it=2500)
print(x, f, num_it)
%time x, f, num_it = compute_root(my_f, x0=3, x1=6, tol=1.0e-15, max_it=2500)
print(x, f, num_it)

%time x0 = optimize.bisect(testf, 3, 6, xtol=1.0e-80, maxiter=10000, full_output=False, disp=True)
print(x0)
%time x1 = optimize.bisect(my_f, 3, 6, xtol=1.0e-80, maxiter=10000, full_output=False, disp=True)
print(x1)

"FAIIIIILLLLLLLLLL"

Wall time: 0 ns
4.0 0.0 51
Error - iteration count exceeded maximum of  2500
Wall time: 5.01 ms
4.534070196722732 2.1316282072803006e-14 2500
Wall time: 0 ns
3.999999999999999
Wall time: 0 ns
4.5340701967227295
